package postgres

import (
	"context"
	"fmt"
	"slices"
	"strings"
)

// minPasswordLength is the shortest password this panel will set.
//
// These roles sit on an unencrypted LAN port with no per-client allowlist, so the
// password is the entire access boundary — `databases/README.md` says as much.
// Sixteen characters is not a policy borrowed from anywhere; it is the point below
// which a password generated by hand starts to look like one a person invented.
const minPasswordLength = 16

// protectedDatabases are PostgreSQL's own. Dropping template0 or template1 breaks
// database creation for the whole server, and dropping `postgres` removes the
// database the panel connects to in order to do any of this.
var protectedDatabases = []string{"postgres", "template0", "template1"}

// reservedPrefix is what PostgreSQL reserves for its own catalogs and roles.
// Creating something under it is not refused by the server in every case, and the
// results when it is not are confusing enough to be worth refusing here.
const reservedPrefix = "pg_"

// repository is the persistence this service needs.
//
// Declared here, where it is consumed, so the service can be tested against a
// fake without a PostgreSQL server. The pgx-backed implementation in repo.go
// satisfies it without importing it.
type repository interface {
	ListDatabases(ctx context.Context) ([]Database, error)
	CreateDatabase(ctx context.Context, name, owner string) error
	DropDatabase(ctx context.Context, name string) error
	DatabaseExists(ctx context.Context, name string) (bool, error)

	ListRoles(ctx context.Context) ([]Role, error)
	CreateRole(ctx context.Context, req CreateRoleRequest) error
	DropRole(ctx context.Context, name string) error
	RoleExists(ctx context.Context, name string) (bool, error)
	CurrentRole(ctx context.Context) (string, error)

	ListExtensions(ctx context.Context, database string) ([]Extension, error)
	CreateExtension(ctx context.Context, database, name string) error
}

// Service manages the databases and roles on the PostgreSQL server.
type Service struct {
	repo repository
}

// NewService builds the service.
func NewService(repo repository) *Service {
	return &Service{repo: repo}
}

// ListDatabases returns every database on the server.
func (s *Service) ListDatabases(ctx context.Context) ([]Database, error) {
	return s.repo.ListDatabases(ctx)
}

// CreateDatabase creates a database, optionally owned by an existing role.
//
// It does not install any extension. Extensions are per database, so the caller
// asks for the ones it wants afterwards — see CreateExtension. Guessing would
// mean every database carried pgvector whether or not anything used it.
func (s *Service) CreateDatabase(ctx context.Context, req CreateDatabaseRequest) (Database, error) {
	if err := validateName(req.Name); err != nil {
		return Database{}, err
	}
	if strings.HasPrefix(strings.ToLower(req.Name), reservedPrefix) {
		return Database{}, fmt.Errorf("%w: names beginning with %q are reserved by PostgreSQL",
			ErrInvalidName, reservedPrefix)
	}
	if req.Owner != "" {
		if err := validateName(req.Owner); err != nil {
			return Database{}, fmt.Errorf("owner: %w", err)
		}
		exists, err := s.repo.RoleExists(ctx, req.Owner)
		if err != nil {
			return Database{}, err
		}
		if !exists {
			// Checked rather than left to the server: PostgreSQL's own message
			// names the role but not which of the two names in the request it was.
			return Database{}, fmt.Errorf("%w: no role named %q", ErrNotFound, req.Owner)
		}
	}

	exists, err := s.repo.DatabaseExists(ctx, req.Name)
	if err != nil {
		return Database{}, err
	}
	if exists {
		return Database{}, fmt.Errorf("%w: a database named %q", ErrAlreadyExists, req.Name)
	}

	if err := s.repo.CreateDatabase(ctx, req.Name, req.Owner); err != nil {
		return Database{}, err
	}
	return Database{Name: req.Name, Owner: req.Owner}, nil
}

// DropDatabase removes a database and everything in it.
func (s *Service) DropDatabase(ctx context.Context, name string) error {
	if err := validateName(name); err != nil {
		return err
	}
	if slices.Contains(protectedDatabases, strings.ToLower(name)) {
		return fmt.Errorf("%w: %q is one of PostgreSQL's own databases", ErrProtected, name)
	}

	exists, err := s.repo.DatabaseExists(ctx, name)
	if err != nil {
		return err
	}
	if !exists {
		return fmt.Errorf("%w: no database named %q", ErrNotFound, name)
	}
	return s.repo.DropDatabase(ctx, name)
}

// ListRoles returns every role on the server.
func (s *Service) ListRoles(ctx context.Context) ([]Role, error) {
	return s.repo.ListRoles(ctx)
}

// CreateRole creates a role.
//
// Superuser is not offered. The server already has exactly one superuser — the
// account this panel connects as — and a second one created through a web form
// would be an account nobody remembers granting.
func (s *Service) CreateRole(ctx context.Context, req CreateRoleRequest) (Role, error) {
	if err := validateName(req.Name); err != nil {
		return Role{}, err
	}
	if strings.HasPrefix(strings.ToLower(req.Name), reservedPrefix) {
		return Role{}, fmt.Errorf("%w: names beginning with %q are reserved by PostgreSQL", ErrInvalidName, reservedPrefix)
	}
	if req.CanLogin && len(req.Password) < minPasswordLength {
		return Role{}, fmt.Errorf("%w: a login role needs a password of at least %d characters",
			ErrWeakPassword, minPasswordLength)
	}
	if !req.CanLogin && req.Password != "" {
		// Refused rather than ignored: silently discarding a password leaves the
		// caller believing it set one.
		return Role{}, fmt.Errorf("%w: a role that cannot log in has no use for a password", ErrInvalidName)
	}

	exists, err := s.repo.RoleExists(ctx, req.Name)
	if err != nil {
		return Role{}, err
	}
	if exists {
		return Role{}, fmt.Errorf("%w: a role named %q", ErrAlreadyExists, req.Name)
	}

	if err := s.repo.CreateRole(ctx, req); err != nil {
		return Role{}, err
	}
	return Role{
		Name:              req.Name,
		CanLogin:          req.CanLogin,
		CanCreateDatabase: req.CanCreateDatabase,
		CanCreateRole:     req.CanCreateRole,
		ConnectionLimit:   -1,
	}, nil
}

// DropRole removes a role.
func (s *Service) DropRole(ctx context.Context, name string) error {
	if err := validateName(name); err != nil {
		return err
	}
	if strings.HasPrefix(strings.ToLower(name), reservedPrefix) {
		return fmt.Errorf("%w: %q is one of PostgreSQL's own roles", ErrProtected, name)
	}

	// The panel must not drop the account it is connected as. PostgreSQL would
	// refuse anyway once the role owns something, but not reliably, and the
	// failure mode — an admin panel that locked itself out of the server it
	// administers — is bad enough to check for rather than hope about.
	current, err := s.repo.CurrentRole(ctx)
	if err != nil {
		return err
	}
	if strings.EqualFold(current, name) {
		return fmt.Errorf("%w: %q is the account this panel connects as", ErrProtected, name)
	}

	exists, err := s.repo.RoleExists(ctx, name)
	if err != nil {
		return err
	}
	if !exists {
		return fmt.Errorf("%w: no role named %q", ErrNotFound, name)
	}
	return s.repo.DropRole(ctx, name)
}

// ListExtensions returns the extensions installed in one database.
func (s *Service) ListExtensions(ctx context.Context, database string) ([]Extension, error) {
	if err := validateName(database); err != nil {
		return nil, err
	}
	return s.repo.ListExtensions(ctx, database)
}

// CreateExtension installs an extension into one database.
//
// The pgvector image ships `vector`, and `pgcrypto` comes with PostgreSQL, but
// neither is installed anywhere until something asks: an extension is per
// database, so there is no server-wide answer to give.
func (s *Service) CreateExtension(ctx context.Context, database string, req CreateExtensionRequest) (Extension, error) {
	if err := validateName(database); err != nil {
		return Extension{}, err
	}
	if _, err := quoteExtensionName(req.Name); err != nil {
		return Extension{}, fmt.Errorf("extension: %w", err)
	}

	exists, err := s.repo.DatabaseExists(ctx, database)
	if err != nil {
		return Extension{}, err
	}
	if !exists {
		return Extension{}, fmt.Errorf("%w: no database named %q", ErrNotFound, database)
	}

	if err := s.repo.CreateExtension(ctx, database, req.Name); err != nil {
		return Extension{}, err
	}
	return Extension{Name: req.Name}, nil
}

// validateName rejects a name this slice will not put into a statement. It is
// quoteIdentifier used as a gate: the service refuses early, before opening a
// connection, and the repository quotes the same name when it builds the SQL.
func validateName(name string) error {
	_, err := quoteIdentifier(name)
	return err
}
