package postgres

import (
	"context"
	"fmt"
	"slices"
	"strings"
)

// minPasswordLength is the shortest password this panel will set.
//
// These roles sit on an unencrypted LAN port with no per-client allowlist, so the
// password is the entire access boundary — `databases/README.md` says as much.
// Sixteen characters is not a policy borrowed from anywhere; it is the point below
// which a password generated by hand starts to look like one a person invented.
const minPasswordLength = 16

// unlimitedConnections is what PostgreSQL stores for a role with no limit, and
// the floor a connection limit may be set to.
const unlimitedConnections = -1

// maxQueryLength bounds a submitted statement. Far more than any query typed into
// a panel, and small enough that a pasted file is refused here rather than
// producing a parser error about character 400000.
const maxQueryLength = 20_000

// protectedDatabases are PostgreSQL's own. Dropping template0 or template1 breaks
// database creation for the whole server, and dropping `postgres` removes the
// database the panel connects to in order to do any of this.
var protectedDatabases = []string{"postgres", "template0", "template1"}

// reservedPrefix is what PostgreSQL reserves for its own catalogs and roles.
// Creating something under it is not refused by the server in every case, and the
// results when it is not are confusing enough to be worth refusing here.
const reservedPrefix = "pg_"

// repository is the persistence this service needs.
//
// Declared here, where it is consumed, so the service can be tested against a
// fake without a PostgreSQL server. The pgx-backed implementation in repo.go
// satisfies it without importing it.
//
// It is wide on purpose: this is the whole persistence surface of the slice —
// databases, roles, extensions, and the two consoles — and the fake in the test
// implements all of it. Splitting it would only scatter one seam across several.
//
//nolint:interfacebloat // the persistence surface is genuinely this wide.
type repository interface {
	ListDatabases(ctx context.Context) ([]Database, error)
	CreateDatabase(ctx context.Context, name, owner string) error
	DropDatabase(ctx context.Context, name string) error
	DatabaseExists(ctx context.Context, name string) (bool, error)

	ListRoles(ctx context.Context) ([]Role, error)
	CreateRole(ctx context.Context, req CreateRoleRequest) error
	DropRole(ctx context.Context, name string) error
	RoleExists(ctx context.Context, name string) (bool, error)
	CurrentRole(ctx context.Context) (string, error)

	AlterRole(ctx context.Context, name string, req UpdateRoleRequest) error
	AlterDatabaseOwner(ctx context.Context, name, owner string) error

	ListExtensions(ctx context.Context, database string) ([]Extension, error)
	CreateExtension(ctx context.Context, database, name string) error

	Query(ctx context.Context, database, sql string) (QueryResult, error)
	Execute(ctx context.Context, database, sql string) (ExecuteResult, error)
	ListRelations(ctx context.Context, database string) ([]Relation, error)
	Browse(ctx context.Context, database, schema, table, cursor string, pageSize int) (BrowseResult, error)
}

// Service manages the databases and roles on the PostgreSQL server.
type Service struct {
	repo repository
}

// NewService builds the service.
func NewService(repo repository) *Service {
	return &Service{repo: repo}
}

// ListDatabases returns every database on the server.
func (s *Service) ListDatabases(ctx context.Context) ([]Database, error) {
	return s.repo.ListDatabases(ctx)
}

// CreateDatabase creates a database, optionally owned by an existing role.
//
// It does not install any extension. Extensions are per database, so the caller
// asks for the ones it wants afterwards — see CreateExtension. Guessing would
// mean every database carried pgvector whether or not anything used it.
func (s *Service) CreateDatabase(ctx context.Context, req CreateDatabaseRequest) (Database, error) {
	if err := validateName(req.Name); err != nil {
		return Database{}, err
	}
	if strings.HasPrefix(strings.ToLower(req.Name), reservedPrefix) {
		return Database{}, fmt.Errorf("%w: names beginning with %q are reserved by PostgreSQL",
			ErrInvalidName, reservedPrefix)
	}
	if req.Owner != "" {
		if err := validateName(req.Owner); err != nil {
			return Database{}, fmt.Errorf("owner: %w", err)
		}
		exists, err := s.repo.RoleExists(ctx, req.Owner)
		if err != nil {
			return Database{}, err
		}
		if !exists {
			// Checked rather than left to the server: PostgreSQL's own message
			// names the role but not which of the two names in the request it was.
			return Database{}, fmt.Errorf("%w: no role named %q", ErrNotFound, req.Owner)
		}
	}

	exists, err := s.repo.DatabaseExists(ctx, req.Name)
	if err != nil {
		return Database{}, err
	}
	if exists {
		return Database{}, fmt.Errorf("%w: a database named %q", ErrAlreadyExists, req.Name)
	}

	if err := s.repo.CreateDatabase(ctx, req.Name, req.Owner); err != nil {
		return Database{}, err
	}
	return Database{Name: req.Name, Owner: req.Owner}, nil
}

// DropDatabase removes a database and everything in it.
func (s *Service) DropDatabase(ctx context.Context, name string) error {
	if err := validateName(name); err != nil {
		return err
	}
	if slices.Contains(protectedDatabases, strings.ToLower(name)) {
		return fmt.Errorf("%w: %q is one of PostgreSQL's own databases", ErrProtected, name)
	}

	exists, err := s.repo.DatabaseExists(ctx, name)
	if err != nil {
		return err
	}
	if !exists {
		return fmt.Errorf("%w: no database named %q", ErrNotFound, name)
	}
	return s.repo.DropDatabase(ctx, name)
}

// ListRoles returns every role on the server.
func (s *Service) ListRoles(ctx context.Context) ([]Role, error) {
	return s.repo.ListRoles(ctx)
}

// CreateRole creates a role.
//
// Superuser is not offered. The server already has exactly one superuser — the
// account this panel connects as — and a second one created through a web form
// would be an account nobody remembers granting.
func (s *Service) CreateRole(ctx context.Context, req CreateRoleRequest) (Role, error) {
	if err := validateName(req.Name); err != nil {
		return Role{}, err
	}
	if strings.HasPrefix(strings.ToLower(req.Name), reservedPrefix) {
		return Role{}, fmt.Errorf("%w: names beginning with %q are reserved by PostgreSQL", ErrInvalidName, reservedPrefix)
	}
	if req.CanLogin && len(req.Password) < minPasswordLength {
		return Role{}, fmt.Errorf("%w: a login role needs a password of at least %d characters",
			ErrWeakPassword, minPasswordLength)
	}
	if !req.CanLogin && req.Password != "" {
		// Refused rather than ignored: silently discarding a password leaves the
		// caller believing it set one.
		return Role{}, fmt.Errorf("%w: a role that cannot log in has no use for a password", ErrInvalidName)
	}

	exists, err := s.repo.RoleExists(ctx, req.Name)
	if err != nil {
		return Role{}, err
	}
	if exists {
		return Role{}, fmt.Errorf("%w: a role named %q", ErrAlreadyExists, req.Name)
	}

	if err := s.repo.CreateRole(ctx, req); err != nil {
		return Role{}, err
	}
	return Role{
		Name:              req.Name,
		CanLogin:          req.CanLogin,
		CanCreateDatabase: req.CanCreateDatabase,
		CanCreateRole:     req.CanCreateRole,
		ConnectionLimit:   -1,
	}, nil
}

// DropRole removes a role.
func (s *Service) DropRole(ctx context.Context, name string) error {
	if err := validateName(name); err != nil {
		return err
	}
	if strings.HasPrefix(strings.ToLower(name), reservedPrefix) {
		return fmt.Errorf("%w: %q is one of PostgreSQL's own roles", ErrProtected, name)
	}

	// The panel must not drop the account it is connected as. PostgreSQL would
	// refuse anyway once the role owns something, but not reliably, and the
	// failure mode — an admin panel that locked itself out of the server it
	// administers — is bad enough to check for rather than hope about.
	current, err := s.repo.CurrentRole(ctx)
	if err != nil {
		return err
	}
	if strings.EqualFold(current, name) {
		return fmt.Errorf("%w: %q is the account this panel connects as", ErrProtected, name)
	}

	exists, err := s.repo.RoleExists(ctx, name)
	if err != nil {
		return err
	}
	if !exists {
		return fmt.Errorf("%w: no role named %q", ErrNotFound, name)
	}
	return s.repo.DropRole(ctx, name)
}

// ListExtensions returns the extensions installed in one database.
func (s *Service) ListExtensions(ctx context.Context, database string) ([]Extension, error) {
	if err := validateName(database); err != nil {
		return nil, err
	}
	return s.repo.ListExtensions(ctx, database)
}

// CreateExtension installs an extension into one database.
//
// The pgvector image ships `vector`, and `pgcrypto` comes with PostgreSQL, but
// neither is installed anywhere until something asks: an extension is per
// database, so there is no server-wide answer to give.
func (s *Service) CreateExtension(ctx context.Context, database string, req CreateExtensionRequest) (Extension, error) {
	if err := validateName(database); err != nil {
		return Extension{}, err
	}
	if _, err := quoteExtensionName(req.Name); err != nil {
		return Extension{}, fmt.Errorf("extension: %w", err)
	}

	exists, err := s.repo.DatabaseExists(ctx, database)
	if err != nil {
		return Extension{}, err
	}
	if !exists {
		return Extension{}, fmt.Errorf("%w: no database named %q", ErrNotFound, database)
	}

	if err := s.repo.CreateExtension(ctx, database, req.Name); err != nil {
		return Extension{}, err
	}
	return Extension{Name: req.Name}, nil
}

// validateName rejects a name this slice will not put into a statement. It is
// quoteIdentifier used as a gate: the service refuses early, before opening a
// connection, and the repository quotes the same name when it builds the SQL.
func validateName(name string) error {
	_, err := quoteIdentifier(name)
	return err
}

// UpdateRole sets a role's flags, connection limit, and optionally its password.
//
// The connecting role is refused. It is the superuser this panel administers the
// server as, and clearing its LOGIN through a form would lock the panel out of
// the server it is being used to administer — with no way back in through the
// panel.
func (s *Service) UpdateRole(ctx context.Context, name string, req UpdateRoleRequest) (Role, error) {
	if err := validateRoleUpdate(name, req); err != nil {
		return Role{}, err
	}

	current, err := s.repo.CurrentRole(ctx)
	if err != nil {
		return Role{}, err
	}
	// EqualFold, matching the drop path a few functions up. The same invariant
	// spelled two ways in one file is how a name differing only in case ends up
	// refused by one and accepted by the other.
	if strings.EqualFold(current, name) {
		return Role{}, fmt.Errorf(
			"%w: %q is the role the panel connects as; changing it here could lock the panel out",
			ErrProtected, name)
	}

	// Read the role rather than just checking it exists: whether it is a
	// superuser changes whether this may proceed at all.
	roles, err := s.repo.ListRoles(ctx)
	if err != nil {
		return Role{}, err
	}
	existing, found := findRole(roles, name)
	if !found {
		return Role{}, fmt.Errorf("%w: no role named %q", ErrNotFound, name)
	}
	if existing.IsSuperuser {
		// Refused rather than carried out. This slice writes NOSUPERUSER on every
		// path and the panel has no control for the attribute, so saving an edit to
		// a superuser role would quietly demote it — a change nobody asked for, in
		// the one direction that is hard to notice and easy to regret.
		return Role{}, fmt.Errorf(
			"%w: %q is a superuser; the panel has no control for that attribute and "+
				"saving would silently remove it",
			ErrProtected, name)
	}

	if err := s.repo.AlterRole(ctx, name, req); err != nil {
		return Role{}, err
	}
	return Role{
		Name:              name,
		CanLogin:          req.CanLogin,
		CanCreateDatabase: req.CanCreateDatabase,
		CanCreateRole:     req.CanCreateRole,
		ConnectionLimit:   req.ConnectionLimit,
	}, nil
}

// UpdateDatabase reassigns a database to another role.
func (s *Service) UpdateDatabase(ctx context.Context, name string, req UpdateDatabaseRequest) error {
	if err := validateName(name); err != nil {
		return err
	}
	if err := validateName(req.Owner); err != nil {
		return fmt.Errorf("owner: %w", err)
	}
	if slices.Contains(protectedDatabases, name) {
		return fmt.Errorf("%w: %q is one of PostgreSQL's own databases", ErrProtected, name)
	}

	// Both checked rather than left to the server: PostgreSQL's message names the
	// object but not which of the two names in the request it was.
	exists, err := s.repo.DatabaseExists(ctx, name)
	if err != nil {
		return err
	}
	if !exists {
		return fmt.Errorf("%w: no database named %q", ErrNotFound, name)
	}

	ownerExists, err := s.repo.RoleExists(ctx, req.Owner)
	if err != nil {
		return err
	}
	if !ownerExists {
		return fmt.Errorf("%w: no role named %q", ErrNotFound, req.Owner)
	}

	return s.repo.AlterDatabaseOwner(ctx, name, req.Owner)
}

// Query runs one read-only statement against a database.
//
// Nothing here inspects the SQL, deliberately. The read-only guarantee comes from
// PostgreSQL — the statement runs in a READ ONLY transaction that is always
// rolled back — and adding a pattern match over the text on top would suggest the
// safety came from here. It would not: comments, CTEs, dollar quoting, and DO
// blocks all defeat one, and a caller who got past it would find nothing behind.
//
// What is checked is that there is a statement at all, and that it is not so
// large that the useful failure is the parser's.
func (s *Service) Query(ctx context.Context, database, sql string) (QueryResult, error) {
	if err := validateName(database); err != nil {
		return QueryResult{}, err
	}
	if strings.TrimSpace(sql) == "" {
		return QueryResult{}, fmt.Errorf("%w: there is no statement to run", ErrInvalidName)
	}
	if len(sql) > maxQueryLength {
		return QueryResult{}, fmt.Errorf("%w: a statement may be at most %d characters",
			ErrInvalidName, maxQueryLength)
	}
	return s.repo.Query(ctx, database, sql)
}

// ListRelations returns the tables and views in one database, each with its
// columns, so the console can show a schema tree rather than leaving an operator
// to guess table names.
func (s *Service) ListRelations(ctx context.Context, database string) ([]Relation, error) {
	if err := validateName(database); err != nil {
		return nil, err
	}
	return s.repo.ListRelations(ctx, database)
}

// Browse returns one keyset-paginated page of a table or view.
//
// The schema and table are validated here, before a connection is opened, for the
// same reason every other name in this slice is: they are interpolated into the
// statement, so the allowlist is what stands between the caller and an injection.
// The cursor is not validated here — it is opaque, and the repository is what
// knows whether it decodes and matches the key.
func (s *Service) Browse(ctx context.Context, database string, req BrowseRequest) (BrowseResult, error) {
	if err := validateName(database); err != nil {
		return BrowseResult{}, err
	}
	if err := validateName(req.Schema); err != nil {
		return BrowseResult{}, fmt.Errorf("schema: %w", err)
	}
	if err := validateName(req.Table); err != nil {
		return BrowseResult{}, fmt.Errorf("table: %w", err)
	}
	return s.repo.Browse(ctx, database, req.Schema, req.Table, req.Cursor, req.PageSize)
}

// Execute runs one statement that may change the database and commits it.
//
// The read-only console's twin, and the reason they are two methods rather than a
// flag: the difference between them is the whole safety story. Query runs in a
// transaction that is always rolled back; Execute runs in one that commits. Both
// gates are checked here — that there is a statement, and that it is not
// oversized — but nothing inspects what it does, the same as Query: PostgreSQL is
// what runs it, and the caller has already been authorized to write by the panel.
func (s *Service) Execute(ctx context.Context, database, sql string) (ExecuteResult, error) {
	if err := validateName(database); err != nil {
		return ExecuteResult{}, err
	}
	if strings.TrimSpace(sql) == "" {
		return ExecuteResult{}, fmt.Errorf("%w: there is no statement to run", ErrInvalidName)
	}
	if len(sql) > maxQueryLength {
		return ExecuteResult{}, fmt.Errorf("%w: a statement may be at most %d characters",
			ErrInvalidName, maxQueryLength)
	}
	return s.repo.Execute(ctx, database, sql)
}

// validateRoleUpdate checks everything about an update that needs no server.
//
// Separate from UpdateRole so the branching lives in one small function rather
// than making the flow of the operation itself hard to read.
func validateRoleUpdate(name string, req UpdateRoleRequest) error {
	if err := validateName(name); err != nil {
		return err
	}
	if strings.HasPrefix(strings.ToLower(name), reservedPrefix) {
		return fmt.Errorf("%w: %q is one of PostgreSQL's own roles", ErrProtected, name)
	}
	if req.CanLogin && req.Password != "" && len(req.Password) < minPasswordLength {
		return fmt.Errorf("%w: a password must be at least %d characters",
			ErrWeakPassword, minPasswordLength)
	}
	if !req.CanLogin && req.Password != "" {
		// Refused rather than ignored, the same as on create: silently discarding
		// a password leaves the caller believing it set one.
		return fmt.Errorf("%w: a role that cannot log in has no use for a password", ErrInvalidName)
	}
	if req.ConnectionLimit < unlimitedConnections {
		return fmt.Errorf("%w: a connection limit is a count, or %d for unlimited",
			ErrInvalidName, unlimitedConnections)
	}
	return nil
}

// findRole looks one role up in a listing.
func findRole(roles []Role, name string) (Role, bool) {
	for _, role := range roles {
		if role.Name == name {
			return role, true
		}
	}
	return Role{}, false
}
