apiVersion: v1
kind: Service
metadata:
  name: admin-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: admin-web
    {{- include "home-lab-admin.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: admin-web
  ports:
    - name: http
      port: 80
      targetPort: http
