#!/usr/bin/env bash
set -euo pipefail

mac=${!#}
case "$mac" in
  52:54:00:00:00:11) address=192.0.2.20 ;;
  52:54:00:00:00:12) address=192.0.2.21 ;;
  *) exit 1 ;;
esac

printf '%s\n' ' Expiry Time           MAC address         Protocol   IP address       Hostname   Client ID or DUID'
printf '%s\n' '---------------------------------------------------------------------------------------------------------'
printf ' 2026-08-25 12:00:00   %s   ipv4       %s/24   -          -\n' "$mac" "$address"
